Tests/Entity/DocumentTest.php
<?php

namespace Erichard\DmsBundle\Tests\Entity;

use Erichard\DmsBundle\Entity\Document;
use Erichard\DmsBundle\Entity\DocumentNode;

class DocumentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @expectedException RuntimeException
     */
    public function test_computed_filename_with_exception()
    {
        $node = new DocumentNode();
        $document = new Document($node);

        $document->getComputedFilename();
    }

    /**
     * @dataProvider getDocuments
     */
    public function test_computed_filename($document, $filename)
    {
        $this->assertEquals($filename, $document->getComputedFilename());
    }

    public function getDocuments()
    {
        $node = new DocumentNode();
        $document1 = new Document($node);
        $document1->setId(1)->setOriginalName('test.jpg');

        $document2 = new Document($node);
        $document2->setId(1234)->setOriginalName('test.doc');

        $document3 = new Document($node);
        $document3->setId(123400)->setOriginalName('test');

        return array(
            array(
                $document1,
                '00/00/00/00000001.jpg'
            ),
            array(
                $document2,
                '00/00/12/00001234.doc'
            ),
            array(
                $document3,
                '00/12/34/00123400.noext'
            ),
        );
    }
}

Form/NodeMetadataType.php
<?php

namespace Erichard\DmsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class NodeMetadataType extends AbstractType
{
    protected $em;

    public function __construct($em)
    {
        $this->em = $em;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $metadatas = $this->em->getRepository('Erichard\DmsBundle\Entity\Metadata')->findByScope(array('node', 'both'));

        foreach ($metadatas as $m) {
            $builder->add($m->getName(), $m->getType(), array_merge(array(
                'label' => $m->getLabel(),
                'required' => $m->isRequired(),
            ), $m->getAttributes()));
        }
    }

    public function getName()
    {
        return 'node_metadata';
    }
}

Form/NodeSelectorType.php
<?php

namespace Erichard\DmsBundle\Form;

use Doctrine\Bundle\DoctrineBundle\Registry;
use Erichard\DmsBundle\Form\Transformer\NodeToIdTransformer;
use Erichard\DmsBundle\Iterator\GedmoTreeIterator;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class NodeSelectorType extends AbstractType
{
    protected $registry;

    public function __construct(Registry $registry)
    {
        $this->registry = $registry;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer(new NodeToIdTransformer($this->registry));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $choices = array();

        $repository = $this
            ->registry
            ->getRepository('Erichard\DmsBundle\Entity\DocumentNode')
        ;

        $tree = $repository
            ->getNodesHierarchyQueryBuilder(null, false, array(
                'childSort' => array('field' => 'name', 'dir' => 'asc')), true)
            ->getQuery()
            ->getArrayResult()
        ;

        $tree = $repository->buildTree($tree);

        // On met en place notre itérator en vue de retirer la profondeur de nos éléments
        $iterator = new \RecursiveIteratorIterator(
            new GedmoTreeIterator($tree), \RecursiveIteratorIterator::SELF_FIRST
        );

        foreach ($iterator as $node) {
            $depth = $iterator->getDepth();
            $choices[$node['id']] = str_repeat("&nbsp;&nbsp;&nbsp;", $depth).$node['name'];
        }

        $resolver->setDefaults(array(
            'choices'       => $choices
        ));
    }

    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'dms_node_selector';
    }
}

Controller/NodeController.php
<?php

namespace Erichard\DmsBundle\Controller;

use Erichard\DmsBundle\Entity\DocumentNode;
use Erichard\DmsBundle\Entity\DocumentNodeAuthorization;
use Erichard\DmsBundle\Entity\DocumentNodeMetadata;
use Erichard\DmsBundle\Event\DmsEvents;
use Erichard\DmsBundle\Event\DmsNodeEvent;
use Erichard\DmsBundle\Security\Acl\Permission\DmsMaskBuilder;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class NodeController extends Controller
{
    public function listAction($node)
    {
        $documentNode = $this->findNodeOrThrowError($node);
        $this->get('dms.manager')->getNodeMetadatas($documentNode);

        foreach ($documentNode->getDocuments() as $document) {
            $filename = $this->container->getParameter('dms.storage.path').'/'.$document->getFilename();

            if (is_file($filename) && is_readable($filename)) {
                $document->setFilesize(filesize($filename));
            }
        }

        if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_ACCESS)) {
            $event = new DmsNodeEvent($documentNode);
            $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_ACCESS, $event);
        }

        return $this->render('ErichardDmsBundle:Node:list.html.twig', array(
            'node'       => $documentNode,
            'mode'       => $this->get('request')->query->get('mode', 'table'),
            'show_nodes' => $this->container->getParameter('dms.workspace.show_nodes')
        ));
    }

    public function indexAction()
    {
        $dmsManager = $this->get('dms.manager');

        $response = $this->render('ErichardDmsBundle:Node:index.html.twig', array(
            'nodes' => $dmsManager->getRoots()
        ));

        return $response;
    }

    public function addAction($node)
    {
        $documentNode = $this->findNodeOrThrowError($node);

        $form = $this->createForm('dms_node');

        if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_ADD)) {
            $event = new DmsNodeEvent($documentNode);
            $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_ADD, $event);
        }

        return $this->render('ErichardDmsBundle:Node:add.html.twig', array(
            'node' => $documentNode,
            'form' => $form->createView()
        ));
    }

    public function editAction($node)
    {
        $request = $this->get('request');
        $this->setCurrentTranslation($request->get('_translation', \Locale::getDefault()));

        $documentNode = $this->findNodeOrThrowError($node);

        $this->get('dms.manager')->getNodeMetadatas($documentNode);

        $form = $this->createForm('dms_node', $documentNode);

        if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_EDIT)) {
            $event = new DmsNodeEvent($documentNode);
            $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_EDIT, $event);
        }

        return $this->render('ErichardDmsBundle:Node:edit.html.twig', array(
            'node' => $documentNode,
            'form' => $form->createView()
        ));
    }

    public function createAction($node)
    {
        $em = $this->get('doctrine')->getManager();
        $parentNode = $this->findNodeOrThrowError($node);

        $newNode    = new DocumentNode();
        $newNode->setParent($parentNode);
        $form       = $this->createForm('dms_node', $newNode);

        $form->bind($this->get('request'));

        if (!$form->isValid()) {
            $response = $this->render('ErichardDmsBundle:Node:add.html.twig', array(
                'node' => $parentNode,
                'form' => $form->createView()
            ));
        } else {

            $metadatas = $form->get('metadatas')->getData();
            foreach ($metadatas as $metaName => $metaValue) {
                if (null !== $metaValue) {
                    $metadata = new DocumentNodeMetadata(
                        $em->getRepository('Erichard\DmsBundle\Entity\Metadata')->findOneByName($metaName)
                    );
                    $metadata->setValue($metaValue);
                    $newNode->addMetadata($metadata);
                    $em->persist($metadata);
                }
            }

            $em->persist($newNode);
            $em->flush();

            if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_CREATE)) {
                $event = new DmsNodeEvent($newNode);
                $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_CREATE, $event);
            }

            $this->get('session')->getFlashBag()->add('success', 'documentNode.add.successfully_created');

            $response = $this->redirect($this->generateUrl('erichard_dms_node_list', array('node' => $node)));
        }

        return $response;
    }

    public function updateAction($node)
    {
        $request = $this->get('request');

        $documentNode = $this->findNodeOrThrowError($node);

        $form = $this->createForm('dms_node', $documentNode);
        $form->bind($this->get('request'));

        if (!$form->isValid()) {
            $response = $this->render('ErichardDmsBundle:Node:edit.html.twig', array(
                'node' => $documentNode,
                'form' => $form->createView()
            ));
        } else {

            $em = $this->get('doctrine')->getManager();

            $metadatas = $form->get('metadatas')->getData();
            foreach ($metadatas as $metaName => $metaValue) {

                if (empty($metaValue)) {
                    if ($metadata = $documentNode->getMetadata($metaName)) {
                        $documentNode->removeMetadataByName($metaName);
                        $em->remove($metadata);
                    }
                    continue;
                }

                if (!$documentNode->hasMetadata($metaName)) {
                    $metadata = new DocumentNodeMetadata(
                        $em->getRepository('Erichard\DmsBundle\Entity\Metadata')->findOneByName($metaName)
                    );
                    $metadata->setValue($metaValue);
                    $documentNode->addMetadata($metadata);
                }

                $metadata = $documentNode->getMetadata($metaName);
                $metadata
                    ->setLocale($documentNode->getLocale())
                    ->setValue($metaValue)
                ;

                $em->persist($documentNode->getMetadata($metaName));
            }

            $em->persist($documentNode);
            $em->flush();

            if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_UPDATE)) {
                $event = new DmsNodeEvent($documentNode);
                $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_UPDATE, $event);
            }

            $this->get('session')->getFlashBag()->add('success', 'documentNode.edit.successfully_updated');

            $response = $this->redirect($this->generateUrl('erichard_dms_node_list', array('node' => $documentNode->getSlug())));
        }

        return $response;
    }

    public function deleteAction($node)
    {
        $documentNode = $this->findNodeOrThrowError($node);

        $redirectUrl = $this->generateUrl('erichard_dms_node_list', array('node' => $documentNode->getParent()->getSlug()));

        $em = $this->get('doctrine')->getManager();
        $em->refresh($documentNode);
        $em->remove($documentNode);
        $em->flush();

        if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_DELETE)) {
            $event = new DmsNodeEvent($documentNode);
            $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_DELETE, $event);
        }

        $this->get('session')->getFlashBag()->add('success', 'documentNode.remove.successfully_removed');

        return $this->redirect($redirectUrl);
    }

    public function removeAction($node)
    {
        $documentNode = $this->findNodeOrThrowError($node);

        return $this->render('ErichardDmsBundle:Node:remove.html.twig', array(
            'node' => $documentNode,
        ));
    }

    public function manageAction($node)
    {
        $documentNode = $this->findNodeOrThrowError($node);

        $roles = $this->container->get('dms.security.role_provider')->getRoles();
        $acl = $this->container->get('dms.security.access.control_list');

        $reflClass = new \ReflectionClass('Erichard\DmsBundle\Security\Acl\Permission\DmsMaskBuilder');

        $authorizations = array();
        foreach ($roles as $role) {
            $authorizationsMask = $acl
                ->getDocumentNodeAuthorizationMask($documentNode, array($role))
            ;

            $authorizations[$role] = array(
                'VIEW'                 => 0,
                'DOCUMENT_ADD'         => 0,
                'DOCUMENT_EDIT'        => 0,
                'DOCUMENT_DELETE'      => 0,
                'DOCUMENT_DOWNLOAD'    => 0,
                'NODE_ADD'             => 0,
                'NODE_EDIT'            => 0,
                'NODE_DELETE'          => 0,
                'NODE_DOWNLOAD'        => 0,
                'MANAGE'               => 0,
            );

            foreach ($authorizations[$role] as $permission => $value) {
                $permissionBit = $reflClass->getConstant('MASK_'.$permission);
                $authorizations[$role][$permission] = $permissionBit === ($authorizationsMask & $permissionBit);
            }
        }

        if ($this->get('event_dispatcher')->hasListeners(DmsEvents::NODE_MANAGE)) {
            $event = new DmsNodeEvent($documentNode);
            $this->get('event_dispatcher')->dispatch(DmsEvents::NODE_MANAGE, $event);
        }

        return $this->render('ErichardDmsBundle:Node:manage.html.twig', array(
            'node' => $documentNode,

Resources/views/Node/_actions.html.twig
{% if node is defined %}
<ul class="nav nav-list">

  <li class="nav-header">Actions</li>
  {#% if is_granted('NODE_DOWNLOAD', node) %}
  <li><a class="disabled" href=""><i class="icon-download-alt"></i>Download</a></li>
  {% endif %#}
  {% if is_granted('NODE_EDIT', node) %}
  <li><a href="{{ path('erichard_dms_edit_node', {'node' : node.slug}) }}"><i class="icon-edit"></i>Edit folder</a></li>
  {% endif %}
  {% if is_granted('NODE_ADD', node) %}
  <li><a href="{{ path('erichard_dms_add_node', {'node' : node.slug}) }}"><i class="icon-plus"></i>Add folder</a></li>
  {% endif %}
  {% if is_granted('NODE_DELETE', node) %}
  <li><a href="{{ path('erichard_dms_remove_node', {'node' : node.slug}) }}"><i class="icon-remove"></i>Remove folder</a></li>
  {% endif %}

  {#% if is_granted('MANAGE', node) %}
  <li><a class="disabled" href="#"><i class="icon-lock"></i>Manage permission</a></li>
  {% endif %#}

  <li class="nav-header">Display modes</li>
  {% if node.documents is not empty %}
  <li><a href="{{ path('erichard_dms_node_list', {'node' : node.slug, 'mode' : 'showcase'}) }}"><i class="icon-play-circle"></i>Showcase</a></li>
  {% endif %}
  <li><a href="{{ path('erichard_dms_node_list', {'node' : node.slug, 'mode' : 'gallery'}) }}"><i class="icon-th-large"></i>Gallery</a></li>
  <li><a href="{{ path('erichard_dms_node_list', {'node' : node.slug, 'mode' : 'content'}) }}"><i class="icon-th-list"></i>Content</a></li>
  <li><a href="{{ path('erichard_dms_node_list', {'node' : node.slug, 'mode' : 'table'}) }}"><i class="icon-table"></i>Table</a></li>
</ul>
{% endif %}

Resources/views/Node/_content.html.twig
<ul class="media-list">
    {% for node in nodes %}
     <li class="media">
        <a class="pull-left" href="#">
           <i class="icon-folder-close"></i>
        </a>
        <div class="media-body">
          <h4 class="media-heading"> <a href="{{ path('erichard_dms_node_list', { 'node' : node.slug }) }}" title="{{ node.name }}">{{ node.name }}</a></h4>
        </div>
      </li>
    {% endfor %}


  {% for document in documents %}
  <li class="media">
    <a class="pull-left" href="{{ path('erichard_dms_show_document', { 'node' : node.slug, 'document' : document.slug }) }}">
      <img class="media-object" src="{{ thumbUrl(document, parameter('dms.content.image_size')) }}" />
    </a>
    <div class="media-body">
      <h4 class="media-heading"><a href="{{ path('erichard_dms_show_document', { 'node' : node.slug, 'document' : document.slug }) }}">{{ document.name }}</a></h4>
    </div>
  </li>
  {% endfor %}
</ul>

Resources/views/Node/_gallery.html.twig
{% set spanValue = (12 / parameter('dms.gallery.items_per_row'))|number_format(0) %}

<div class="row-fluid">
{% for node in nodes %}
  <div class="span{{ spanValue }}">
    <a href="{{ path('erichard_dms_node_list', { 'node' : node.slug }) }}" title="{{ node.name }}">
        <i class="icon-folder-close"></i><br/>
        {{ node.name }}
    </a>
  </div>

  {% if loop.index is divisibleby(parameter('dms.gallery.items_per_row')) %}
    </div>
    {% if not loop.last %}<div class="row-fluid">{% endif %}
  {% endif %}
{% endfor %}

{% for document in documents %}
  <div class="span{{ spanValue }}">
    <a href="{{ path('erichard_dms_show_document', { 'node' : node.slug, 'document' : document.slug }) }}" class="thumbnail" title="{{ document.name }}">
        <img src="{{ thumbUrl(document, parameter('dms.gallery.image_size')) }}" />
    </a>
    <p>{{ document.name }}</p>
  </div>

  {% if loop.index is divisibleby(parameter('dms.gallery.items_per_row')) %}
    </div>
    {% if not loop.last %}<div class="row-fluid">{% endif %}
  {% endif %}

  {% if loop.last %}
    <div class="span{{ spanValue }}">
    {% if is_granted('DOCUMENT_ADD', node) %}
    <a href="{{ path('erichard_dms_add_document', { 'node': node.slug }) }}" class="thumbnail" title="{{ document.name }}">
        <img src="http://placehold.it/{{ parameter('dms.gallery.image_size') }}&text=Add documents" />
    </a>
    {% endif %}
    </div>
  {% endif %}
{% endfor %}
</div>

Resources/views/Node/_showcase.html.twig
<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    {% for document in documents %}
      <li data-target="#myCarousel" data-slide-to="{{ loop.index }}" {% if loop.first %}%class="active"{% endif %}></li>
    {% endfor %}
  </ol>

  <!-- Carousel items -->
  <div class="carousel-inner">
    {% for document in documents %}
        <div class="item{% if loop.first %} active{% endif %}">
          <img src="{{ thumbUrl(document, parameter('dms.showcase.image_size')) }}" />
          <div class="carousel-caption">
              <h4>{{ document.name }}</h4>
          </div>
        </div>
    {% endfor %}
  </div>

  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

Resources/views/Node/_table.html.twig
<table class="table table-striped table-hover">
{% for node in nodes %}
  <tr>
    <td>
      <i class="icon-folder-close"></i>
    </td>
    <td><h4 class="media-heading"> <a href="{{ path('erichard_dms_node_list', { 'node' : node.slug }) }}" title="{{ node.name }}">{{ node.name }}</a></td>
    <td></td>
  </tr>
{% endfor %}

{% for document in documents %}
  <tr>
    <td >
      <a href="{{ path('erichard_dms_show_document', { 'node' : node.slug, 'document' : document.slug }) }}" class="thumbnail" title="{{ document.name }}">
          <img src="{{ thumbUrl(document, parameter('dms.table.image_size')) }}" />
      </a>
    </td>
    <td><a href="{{ path('erichard_dms_show_document', { 'node' : node.slug, 'document' : document.slug }) }}">{{ document.name }}</a></td>
    <td></td>
    <td>{{ document.mimeType }}</td>
  </tr>
{% endfor %}
</table>

Resources/views/Node/_tree.html.twig
{% if node is defined %}
  <h2><i class="icon-folder-open-alt"></i> {{ node.name }}</h2>
{% else %}
  <h2>Home</h2>
{% endif %}
<ul class="nav nav-tabs nav-stacked">
  {% for node in nodes %}

      <li><a href="{{ path('erichard_dms_node_list', {'node' : node.slug})}}"><i class="icon-folder-close-alt"></i>{{ node.name }}</a></li>
  {% endfor %}
</ul>

<hr>

Resources/views/Node/add.html.twig
{% extends dms_layout|default('ErichardDmsBundle::layout.html.twig') %}

{% block dms_documents %}

    <h1>Add a new folder</h1>

    <form class="form-horizontal" action="{{ path('erichard_dms_create_node', {'node' : node.slug}) }}" method="POST">

        {{ form_widget(form._token) }}
        {{ form_errors(form) }}

        {{ form_row(form.name, {'form_type': 'horizontal'}) }}
        {{ form_row(form.enabled, {'form_type': 'horizontal'}) }}

        {% for metadata in form.metadatas %}
            {{ form_row(metadata, {
                'form_type': 'horizontal',
                'value' : node.getMetadata(metadata.vars.name).value
            }) }}
        {% endfor %}

        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Save changes</button>
          <button type="button" class="btn">Cancel</button>
        </div>
    </form>

{% endblock %}

Resources/views/Node/edit.html.twig
{% extends dms_layout|default('ErichardDmsBundle::layout.html.twig') %}

{% form_theme form _self %}

{% block choice_widget_options %}
{% spaceless %}
    {% for group_label, choice in options %}
        {% if choice is iterable %}
            <optgroup label="{{ group_label|trans({}, translation_domain) }}">
                {% set options = choice %}
                {{ block('choice_widget_options') }}
            </optgroup>
        {% else %}
            <option value="{{ choice.value }}"{% if choice is selectedchoice(value) %} selected="selected"{% endif %}>{{ choice.label|trans({}, translation_domain)|raw }}</option>
        {% endif %}
    {% endfor %}
{% endspaceless %}
{% endblock choice_widget_options %}

{% block dms_documents %}

    <h1>Edit folder</h1>

    <form class="form-horizontal" action="{{ path('erichard_dms_update_node', {'node' : node.slug}) }}" method="POST">

        {{ form_widget(form._token) }}
        {{ form_widget(form._locale) }}
        {{ form_errors(form) }}

        {{ form_row(form.name, {'form_type': 'horizontal'}) }}
        {{ form_row(form.parent, {'form_type': 'horizontal'}) }}
        {{ form_row(form.enabled, {'form_type': 'horizontal'}) }}

        {% for metadata in form.metadatas %}
            {{ form_row(metadata, {
                'form_type': 'horizontal',
                'value' : node.getMetadata(metadata.vars.name).value|default(node.getMetadata(metadata.vars.name).metadata.defaultValue)
            }) }}
        {% endfor %}

        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Save changes</button>
          <button type="button" class="btn">Cancel</button>
        </div>
    </form>

{% endblock %}

Resources/views/Node/index.html.twig
{% extends dms_layout|default('ErichardDmsBundle::layout.html.twig') %}

{% block dms_breacrumb %}{% endblock %}

{% block dms_sidebar %}
    {% include 'ErichardDmsBundle:Node:_actions.html.twig' with {'nodes' : nodes} %}
{% endblock %}

{% block dms_documents %}

    {% include 'ErichardDmsBundle:Node:_gallery.html.twig' with {'documents' : [], 'nodes': nodes} %}
{% endblock %}

Resources/views/Node/list.html.twig
{% extends dms_layout|default('ErichardDmsBundle::layout.html.twig') %}

{% block dms_documents %}

    {% include 'ErichardDmsBundle:Node:_%s.html.twig'|format(mode) with {'documents' : node.documents, 'nodes': show_nodes ? node.nodes : []} %}

{% endblock %}

Resources/views/Node/remove.html.twig
{% extends dms_layout|default('ErichardDmsBundle::layout.html.twig') %}

{% block dms_documents %}

    <h1>Remove folder</h1>

    <form class="form-horizontal" action="{{ path('erichard_dms_delete_node', {'node' : node.slug}) }}" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <div class="alert alert-warning alert-block">
            <h4>Warning !</h4>
            <p>
            You are going to delete the <strong>{{ node.name }}</strong> folder and all its files and subfolders.
            </p>
            <p>
            This operation could not be canceled ! Continue anyway ?
            </p>

            <div class="pull-right">
                <a href="{{ path('erichard_dms_node_list', {'node' : node.slug}) }}" class="btn btn-primary">No !</a>
                <button type="submit" class="btn btn-danger">Yes sir !</button>
            </div>

            <div class="clearfix"></div>

        </div>
    </form>

{% endblock %}